/**
 * JIANGSU YUREN GROUP - Global JavaScript
 * Multi-language support + UI interactions
 */

// ============================================
// TRANSLATIONS
// ============================================
const TRANSLATIONS = {
  zh: {
    // 导航
    nav_home: '首页',
    nav_products: '产品中心',
    nav_shoes: '鞋类产品',
    nav_shoes_tactical: '作训鞋',
    nav_shoes_military: '军务鞋',
    nav_uniforms: '职业制服',
    nav_about: '关于我们',
    nav_manufacturing: '生产实力',
    nav_contact: '联系我们',
    nav_get_quote: '获取报价',

    // 首页英雄区
    hero_badge: '政府采购指定供应商',
    hero_title: '专业军警装备制造商',
    hero_subtitle: '江苏玉人集团成立于1990年，36年专注军警职业装备制造，年产能600万+件/双，是国内军警装备领域的重要供应商。',
    hero_cta_primary: '查看产品',
    hero_cta_secondary: '联系我们',
    hero_stat1: '年产能',
    hero_stat1_val: '600万+',
    hero_stat2: '成立年份',
    hero_stat2_val: '1990年',
    hero_stat3: '出口国家',
    hero_stat3_val: '50+',
    hero_stat4: '员工人数',
    hero_stat4_val: '2000+',

    // 产品区
    products_title: '核心产品系列',
    products_subtitle: '专为军警及政府机构设计的专业装备，品质经过严格检验',
    product_tactical_boots: '作训鞋系列',
    product_tactical_boots_desc: '专业作战训练靴，防滑耐磨，适合各种地形',
    product_military_boots: '军务鞋系列',
    product_military_boots_desc: '迷彩军务靴，轻量化设计，长时间穿着舒适',
    product_uniforms: '职业制服',
    product_uniforms_desc: '定制职业制服，面料优质，版型专业',
    product_wool: '羊毛衫系列',
    product_wool_desc: '高品质羊毛制品，保暖舒适',
    product_fabric: '坯布面料',
    product_fabric_desc: '优质坯布，适合各类服装生产',
    btn_view_details: '查看详情',
    btn_get_quote: '获取报价',

    // 信任背书
    trust_title: '为什么选择玉人集团',
    trust_gov: '政府采购供应商',
    trust_gov_desc: '长期为公安、司法等政府部门提供专业装备，产品经过严格的政府采购检验',
    trust_iso: 'ISO质量认证',
    trust_iso_desc: '通过ISO质量管理体系认证，产品符合国家及行业标准',
    trust_years: '36年行业经验',
    trust_years_desc: '自1990年成立以来，专注军警装备制造，积累了丰富的行业经验',
    trust_capacity: '强大生产能力',
    trust_capacity_desc: '年产能600万+件/双，能够快速响应大批量订单需求',

    // 关于我们
    about_title: '关于江苏玉人集团',
    about_subtitle: '36年专注军警职业装备制造',
    about_desc1: '江苏玉人集团成立于1990年，位于江苏省盐城市，是一家专注于军警职业装备制造的企业。',
    about_desc2: '经过36年的发展，公司已成为国内军警装备领域的重要供应商，产品远销50多个国家和地区。',
    about_stat1: '年产能',
    about_stat2: '成立年份',
    about_stat3: '出口国家',
    about_stat4: '员工人数',

    // 联系区
    contact_title: '联系我们',
    contact_subtitle: '获取专业报价和产品咨询',
    contact_name: '姓名',
    contact_email: '邮箱',
    contact_phone: '电话',
    contact_company: '公司',
    contact_message: '留言',
    contact_submit: '发送消息',
    contact_address: '地址',
    contact_address_val: '江苏省盐城市',
    contact_phone_val: '0515-86116888',
    contact_email_val: 'info@yurengroup.com',

    // 页脚
    footer_desc: '江苏玉人集团 - 专业军警装备制造商，36年行业经验，政府采购指定供应商。',
    footer_products: '产品系列',
    footer_company: '公司信息',
    footer_contact: '联系方式',
    footer_rights: '版权所有',

    // 产品页面
    page_products_title: '产品中心',
    page_products_subtitle: '专业军警装备，品质保证',
    page_shoes_title: '鞋类产品',
    page_shoes_subtitle: '专业军警鞋类，耐用舒适',
    page_uniforms_title: '职业制服',
    page_uniforms_subtitle: '定制职业制服，专业品质',
    page_about_title: '关于我们',
    page_manufacturing_title: '生产实力',
    page_contact_title: '联系我们',

    // 作训鞋页面
    tactical_title: '作训鞋系列',
    tactical_subtitle: '专业作战训练靴',
    tactical_color_black: '黑色',
    tactical_color_brown: '棕色',
    tactical_color_sand: '沙色',
    tactical_feature1: '防滑耐磨',
    tactical_feature2: '透气舒适',
    tactical_feature3: '高强度材料',
    tactical_feature4: '快速系带',
    tactical_spec_title: '产品规格',
    tactical_spec_upper: '鞋面材料',
    tactical_spec_sole: '鞋底材料',
    tactical_spec_height: '鞋帮高度',
    tactical_spec_weight: '重量',

    // 军务鞋页面
    military_title: '军务鞋系列',
    military_subtitle: '迷彩军务靴',
    military_color_camo: '迷彩色',
    military_feature1: '迷彩设计',
    military_feature2: '轻量化',
    military_feature3: '防水处理',
    military_feature4: '舒适内衬',

    // 制服页面
    uniform_title: '职业制服系列',
    uniform_subtitle: '专业定制职业制服',
    uniform_type1: '警务制服',
    uniform_type2: '司法制服',
    uniform_type3: '安保制服',
    uniform_type4: '工作服',

    // 生产实力页面
    mfg_title: '生产实力',
    mfg_subtitle: '现代化生产设施，严格质量管控',
    mfg_capacity: '年产能',
    mfg_workers: '员工人数',
    mfg_machines: '生产设备',
    mfg_quality: '质量体系',

    // 面包屑
    breadcrumb_home: '首页',
    breadcrumb_products: '产品中心',
    breadcrumb_shoes: '鞋类产品',
    breadcrumb_uniforms: '职业制服',
  },
  en: {
    nav_home: 'Home',
    nav_products: 'Products',
    nav_shoes: 'Footwear',
    nav_shoes_tactical: 'Tactical Boots',
    nav_shoes_military: 'Military Boots',
    nav_uniforms: 'Uniforms',
    nav_about: 'About Us',
    nav_manufacturing: 'Manufacturing',
    nav_contact: 'Contact',
    nav_get_quote: 'Get Quote',

    hero_badge: 'Government Procurement Supplier',
    hero_title: 'Professional Military & Police Equipment Manufacturer',
    hero_subtitle: 'Jiangsu Yuren Group was founded in 1990. For 36 years, we have focused on manufacturing military and police professional equipment with an annual capacity of 6M+ pieces/pairs.',
    hero_cta_primary: 'View Products',
    hero_cta_secondary: 'Contact Us',
    hero_stat1: 'Annual Capacity',
    hero_stat1_val: '6M+',
    hero_stat2: 'Founded',
    hero_stat2_val: '1990',
    hero_stat3: 'Export Countries',
    hero_stat3_val: '50+',
    hero_stat4: 'Employees',
    hero_stat4_val: '2000+',

    products_title: 'Core Product Lines',
    products_subtitle: 'Professional equipment designed for military, police and government agencies',
    product_tactical_boots: 'Tactical Boots Series',
    product_tactical_boots_desc: 'Professional combat training boots, anti-slip and durable, suitable for various terrains',
    product_military_boots: 'Military Boots Series',
    product_military_boots_desc: 'Camouflage military boots with lightweight design for long-wearing comfort',
    product_uniforms: 'Professional Uniforms',
    product_uniforms_desc: 'Custom professional uniforms with premium fabrics and professional cuts',
    product_wool: 'Wool Sweaters Series',
    product_wool_desc: 'High-quality wool products, warm and comfortable',
    product_fabric: 'Fabric Materials',
    product_fabric_desc: 'Quality greige fabrics suitable for various garment production',
    btn_view_details: 'View Details',
    btn_get_quote: 'Get Quote',

    trust_title: 'Why Choose Yuren Group',
    trust_gov: 'Government Procurement Supplier',
    trust_gov_desc: 'Long-term supplier of professional equipment for public security and judicial departments',
    trust_iso: 'ISO Quality Certified',
    trust_iso_desc: 'ISO quality management system certified, products meet national and industry standards',
    trust_years: '36 Years Experience',
    trust_years_desc: 'Since 1990, focused on military and police equipment manufacturing',
    trust_capacity: 'Strong Production Capacity',
    trust_capacity_desc: 'Annual capacity of 6M+ pieces/pairs, rapid response to large orders',

    about_title: 'About Jiangsu Yuren Group',
    about_subtitle: '36 Years Focused on Military & Police Equipment',
    about_desc1: 'Jiangsu Yuren Group was founded in 1990 in Yancheng, Jiangsu Province, specializing in military and police professional equipment.',
    about_desc2: 'After 36 years of development, the company has become an important supplier in the domestic military and police equipment field, exporting to over 50 countries and regions.',
    about_stat1: 'Annual Capacity',
    about_stat2: 'Founded',
    about_stat3: 'Export Countries',
    about_stat4: 'Employees',

    contact_title: 'Contact Us',
    contact_subtitle: 'Get professional quotes and product consultation',
    contact_name: 'Name',
    contact_email: 'Email',
    contact_phone: 'Phone',
    contact_company: 'Company',
    contact_message: 'Message',
    contact_submit: 'Send Message',
    contact_address: 'Address',
    contact_address_val: 'Yancheng, Jiangsu Province',
    contact_phone_val: '0515-86116888',
    contact_email_val: 'info@yurengroup.com',

    footer_desc: 'Jiangsu Yuren Group - Professional Military & Police Equipment Manufacturer, 36 years of experience, Government Procurement Designated Supplier.',
    footer_products: 'Products',
    footer_company: 'Company',
    footer_contact: 'Contact',
    footer_rights: 'All Rights Reserved',

    page_products_title: 'Products',
    page_products_subtitle: 'Professional military and police equipment, quality guaranteed',
    page_shoes_title: 'Footwear',
    page_shoes_subtitle: 'Professional military and police footwear, durable and comfortable',
    page_uniforms_title: 'Professional Uniforms',
    page_uniforms_subtitle: 'Custom professional uniforms with professional quality',
    page_about_title: 'About Us',
    page_manufacturing_title: 'Manufacturing',
    page_contact_title: 'Contact Us',

    tactical_title: 'Tactical Boots Series',
    tactical_subtitle: 'Professional Combat Training Boots',
    tactical_color_black: 'Black',
    tactical_color_brown: 'Brown',
    tactical_color_sand: 'Sand',
    tactical_feature1: 'Anti-slip & Durable',
    tactical_feature2: 'Breathable & Comfortable',
    tactical_feature3: 'High-strength Materials',
    tactical_feature4: 'Quick Lacing',
    tactical_spec_title: 'Product Specifications',
    tactical_spec_upper: 'Upper Material',
    tactical_spec_sole: 'Sole Material',
    tactical_spec_height: 'Boot Height',
    tactical_spec_weight: 'Weight',

    military_title: 'Military Boots Series',
    military_subtitle: 'Camouflage Military Boots',
    military_color_camo: 'Camouflage',
    military_feature1: 'Camouflage Design',
    military_feature2: 'Lightweight',
    military_feature3: 'Waterproof Treatment',
    military_feature4: 'Comfortable Lining',

    uniform_title: 'Professional Uniforms Series',
    uniform_subtitle: 'Professional Custom Uniforms',
    uniform_type1: 'Police Uniforms',
    uniform_type2: 'Judicial Uniforms',
    uniform_type3: 'Security Uniforms',
    uniform_type4: 'Workwear',

    mfg_title: 'Manufacturing',
    mfg_subtitle: 'Modern production facilities with strict quality control',
    mfg_capacity: 'Annual Capacity',
    mfg_workers: 'Employees',
    mfg_machines: 'Production Equipment',
    mfg_quality: 'Quality System',

    breadcrumb_home: 'Home',
    breadcrumb_products: 'Products',
    breadcrumb_shoes: 'Footwear',
    breadcrumb_uniforms: 'Uniforms',
  },

  ja: {
    nav_home: 'ホーム',
    nav_products: '製品',
    nav_shoes: '靴類',
    nav_shoes_tactical: '戦術ブーツ',
    nav_shoes_military: '軍用ブーツ',
    nav_uniforms: '制服',
    nav_about: '会社概要',
    nav_manufacturing: '製造能力',
    nav_contact: 'お問い合わせ',
    nav_get_quote: '見積もり',

    hero_badge: '政府調達指定サプライヤー',
    hero_title: 'プロフェッショナル軍警装備メーカー',
    hero_subtitle: '江蘇玉人集団は1990年に設立され、36年間軍警職業装備製造に専念しています。',
    hero_cta_primary: '製品を見る',
    hero_cta_secondary: 'お問い合わせ',
    hero_stat1: '年間生産能力',
    hero_stat1_val: '600万+',
    hero_stat2: '設立年',
    hero_stat2_val: '1990年',
    hero_stat3: '輸出国',
    hero_stat3_val: '50+',
    hero_stat4: '従業員数',
    hero_stat4_val: '2000+',

    products_title: '主要製品ライン',
    products_subtitle: '軍警および政府機関向けに設計された専門装備',
    product_tactical_boots: '戦術ブーツシリーズ',
    product_tactical_boots_desc: 'プロの戦闘訓練ブーツ、滑り止めで耐久性',
    product_military_boots: '軍用ブーツシリーズ',
    product_military_boots_desc: '迷彩軍用ブーツ、軽量設計',
    product_uniforms: '職業制服',
    product_uniforms_desc: 'カスタム職業制服、高品質生地',
    product_wool: 'ウールセーターシリーズ',
    product_wool_desc: '高品質ウール製品',
    product_fabric: '生地素材',
    product_fabric_desc: '優れた品質の原反',
    btn_view_details: '詳細を見る',
    btn_get_quote: '見積もりを取得',

    trust_title: 'なぜ玉人集団を選ぶのか',
    trust_gov: '政府調達サプライヤー',
    trust_gov_desc: '政府部門に長年プロ装備を供給',
    trust_iso: 'ISO品質認証',
    trust_iso_desc: 'ISO品質管理システム認証取得',
    trust_years: '36年の業界経験',
    trust_years_desc: '軍警装備製造に専念',
    trust_capacity: '強力な生産能力',
    trust_capacity_desc: '大量注文にも迅速対応',

    about_title: '江蘇玉人集団について',
    about_subtitle: '36年間軍警職業装備製造に専念',
    about_desc1: '江蘇玉人集団は1990年に設立されました。',
    about_desc2: '36年の発展を経て、国内の軍警装備分野の重要なサプライヤーとなりました。',
    about_stat1: '年間生産能力',
    about_stat2: '設立年',
    about_stat3: '輸出国',
    about_stat4: '従業員数',

    contact_title: 'お問い合わせ',
    contact_subtitle: 'プロの見積もり',
    contact_name: 'お名前',
    contact_email: 'メール',
    contact_phone: '電話',
    contact_company: '会社名',
    contact_message: 'メッセージ',
    contact_submit: '送信',
    contact_address: '住所',
    contact_address_val: '中国江蘇省塩城市',
    contact_phone_val: '0515-86116888',
    contact_email_val: 'info@yurengroup.com',

    footer_desc: '江蘇玉人集団 - プロの軍警装備メーカー',
    footer_products: '製品',
    footer_company: '会社情報',
    footer_contact: 'お問い合わせ',
    footer_rights: 'All Rights Reserved',

    page_products_title: '製品センター',
    page_products_subtitle: 'プロの軍警装備',
    page_shoes_title: '靴類製品',
    page_shoes_subtitle: 'プロの軍警用靴',
    page_uniforms_title: '職業制服',
    page_uniforms_subtitle: 'カスタム職業制服',
    page_about_title: '会社概要',
    page_manufacturing_title: '製造能力',
    page_contact_title: 'お問い合わせ',

    tactical_title: '戦術ブーツシリーズ',
    tactical_subtitle: 'プロの戦闘訓練ブーツ',
    tactical_color_black: 'ブラック',
    tactical_color_brown: 'ブラウン',
    tactical_color_sand: 'サンド',
    tactical_feature1: '滑り止め',
    tactical_feature2: '通気性',
    tactical_feature3: '高強度',
    tactical_feature4: 'クイック',
    tactical_spec_title: '製品仕様',
    tactical_spec_upper: 'アッパー',
    tactical_spec_sole: 'ソール',
    tactical_spec_height: '高さ',
    tactical_spec_weight: '重量',

    military_title: '軍用ブーツシリーズ',
    military_subtitle: '迷彩軍用ブーツ',
    military_color_camo: '迷彩',
    military_feature1: '迷彩',
    military_feature2: '軽量',
    military_feature3: '防水',
    military_feature4: '快適',

    uniform_title: '職業制服シリーズ',
    uniform_subtitle: 'プロのカスタム制服',
    uniform_type1: '警察制服',
    uniform_type2: '司法制服',
    uniform_type3: '警備制服',
    uniform_type4: '作業服',

    mfg_title: '製造能力',
    mfg_subtitle: '現代的な生産設備',
    mfg_capacity: '年間生産能力',
    mfg_workers: '従業員数',
    mfg_machines: '生産設備',
    mfg_quality: '品質システム',

    breadcrumb_home: 'ホーム',
    breadcrumb_products: '製品',
    breadcrumb_shoes: '靴類',
    breadcrumb_uniforms: '制服',
  },

  ko: {
    nav_home: '홈',
    nav_products: '제품',
    nav_shoes: '신발류',
    nav_shoes_tactical: '전술 부츠',
    nav_shoes_military: '군용 부츠',
    nav_uniforms: '유니폼',
    nav_about: '회사 소개',
    nav_manufacturing: '제조 역량',
    nav_contact: '문의하기',
    nav_get_quote: '견적 요청',

    hero_badge: '정부 조달 지정 공급업체',
    hero_title: '전문 군경 장비 제조업체',
    hero_subtitle: '장쑤 위런 그룹은 1990년에 설립되어 36년간 군경 장비 제조에 전념하고 있습니다.',
    hero_cta_primary: '제품 보기',
    hero_cta_secondary: '문의하기',
    hero_stat1: '연간 생산 능력',
    hero_stat1_val: '600만+',
    hero_stat2: '설립 연도',
    hero_stat2_val: '1990년',
    hero_stat3: '수출 국가',
    hero_stat3_val: '50+',
    hero_stat4: '직원 수',
    hero_stat4_val: '2000+',

    products_title: '핵심 제품 라인',
    products_subtitle: '군경 및 정부 기관을 위해 설계된 전문 장비',
    product_tactical_boots: '전술 부츠 시리즈',
    product_tactical_boots_desc: '전문 전투 훈련 부츠',
    product_military_boots: '군용 부츠 시리즈',
    product_military_boots_desc: '위장 군용 부츠',
    product_uniforms: '직업 유니폼',
    product_uniforms_desc: '맞춤형 직업 유니폼',
    product_wool: '울 스웨터 시리즈',
    product_wool_desc: '고품질 울 제품',
    product_fabric: '원단 소재',
    product_fabric_desc: '우수한 품질의 원단',
    btn_view_details: '자세히 보기',
    btn_get_quote: '견적 받기',

    trust_title: '왜 위런 그룹을 선택하는가',
    trust_gov: '정부 조달 공급업체',
    trust_gov_desc: '정부 부문에 전문 장비 공급',
    trust_iso: 'ISO 품질 인증',
    trust_iso_desc: 'ISO 품질 관리 시스템 인증',
    trust_years: '36년 업계 경험',
    trust_years_desc: '군경 장비 제조에 전념',
    trust_capacity: '강력한 생산 능력',
    trust_capacity_desc: '대량 주문에도 신속 대응',

    about_title: '장쑤 위런 그룹 소개',
    about_subtitle: '36년간 군경 장비 제조에 전념',
    about_desc1: '장쑤 위런 그룹은 1990년에 설립되었습니다.',
    about_desc2: '36년의 발전을 거쳐 국내 군경 장비 분야의 중요한 공급업체가 되었습니다.',
    about_stat1: '연간 생산 능력',
    about_stat2: '설립 연도',
    about_stat3: '수출 국가',
    about_stat4: '직원 수',

    contact_title: '문의하기',
    contact_subtitle: '전문 견적',
    contact_name: '성함',
    contact_email: '이메일',
    contact_phone: '전화번호',
    contact_company: '회사명',
    contact_message: '메시지',
    contact_submit: '보내기',
    contact_address: '주소',
    contact_address_val: '중국 장쑤성 옌청시',
    contact_phone_val: '0515-86116888',
    contact_email_val: 'info@yurengroup.com',

    footer_desc: '장쑤 위런 그룹 - 전문 군경 장비 제조업체',
    footer_products: '제품',
    footer_company: '회사 정보',
    footer_contact: '연락처',
    footer_rights: 'All Rights Reserved',

    page_products_title: '제품 센터',
    page_products_subtitle: '전문 군경 장비',
    page_shoes_title: '신발류 제품',
    page_shoes_subtitle: '전문 군경용 신발',
    page_uniforms_title: '직업 유니폼',
    page_uniforms_subtitle: '맞춤형 직업 유니폼',
    page_about_title: '회사 소개',
    page_manufacturing_title: '제조 역량',
    page_contact_title: '문의하기',

    tactical_title: '전술 부츠 시리즈',
    tactical_subtitle: '전문 전투 훈련 부츠',
    tactical_color_black: '블랙',
    tactical_color_brown: '브라운',
    tactical_color_sand: '샌드',
    tactical_feature1: '미끄럼 방지',
    tactical_feature2: '통기성',
    tactical_feature3: '고강도',
    tactical_feature4: '퀵',
    tactical_spec_title: '제품 사양',
    tactical_spec_upper: '어퍼',
    tactical_spec_sole: '솔',
    tactical_spec_height: '높이',
    tactical_spec_weight: '무게',

    military_title: '군용 부츠 시리즈',
    military_subtitle: '위장 군용 부츠',
    military_color_camo: '위장',
    military_feature1: '위장 디자인',
    military_feature2: '경량화',
    military_feature3: '방수 처리',
    military_feature4: '편안한 안감',

    uniform_title: '직업 유니폼 시리즈',
    uniform_subtitle: '전문 맞춤형 유니폼',
    uniform_type1: '경찰 유니폼',
    uniform_type2: '사법 유니폼',
    uniform_type3: '보안 유니폼',
    uniform_type4: '작업복',

    mfg_title: '제조 역량',
    mfg_subtitle: '현대적인 생산 시설',
    mfg_capacity: '연간 생산 능력',
    mfg_workers: '직원 수',
    mfg_machines: '생산 장비',
    mfg_quality: '품질 시스템',

    breadcrumb_home: '홈',
    breadcrumb_products: '제품',
    breadcrumb_shoes: '신발류',
    breadcrumb_uniforms: '유니폼',
  },

  fr: {
    nav_home: 'Accueil',
    nav_products: 'Produits',
    nav_shoes: 'Chaussures',
    nav_shoes_tactical: 'Bottes Tactiques',
    nav_shoes_military: 'Bottes Militaires',
    nav_uniforms: 'Uniformes',
    nav_about: 'À Propos',
    nav_manufacturing: 'Fabrication',
    nav_contact: 'Contact',
    nav_get_quote: 'Devis',

    hero_badge: 'Fournisseur Agréé Gouvernemental',
    hero_title: 'Fabricant d\'Équipements Militaires et Policiers Professionnels',
    hero_subtitle: 'Jiangsu Yuren Group a été fondé en 1990. Depuis 36 ans, fabrication d\'équipements professionnels militaires et policiers.',
    hero_cta_primary: 'Voir les Produits',
    hero_cta_secondary: 'Nous Contacter',
    hero_stat1: 'Capacité Annuelle',
    hero_stat1_val: '6M+',
    hero_stat2: 'Fondé en',
    hero_stat2_val: '1990',
    hero_stat3: 'Pays Exportés',
    hero_stat3_val: '50+',
    hero_stat4: 'Employés',
    hero_stat4_val: '2000+',

    products_title: 'Gammes de Produits',
    products_subtitle: 'Équipements professionnels pour militaires, police et agences gouvernementales',
    product_tactical_boots: 'Série Bottes Tactiques',
    product_tactical_boots_desc: 'Bottes d\'entraînement professionnelles',
    product_military_boots: 'Série Bottes Militaires',
    product_military_boots_desc: 'Bottes militaires camouflage',
    product_uniforms: 'Uniformes Professionnels',
    product_uniforms_desc: 'Uniformes professionnels sur mesure',
    product_wool: 'Série Pulls en Laine',
    product_wool_desc: 'Produits en laine de haute qualité',
    product_fabric: 'Matériaux en Tissu',
    product_fabric_desc: 'Étoffes de qualité supérieure',
    btn_view_details: 'Voir Détails',
    btn_get_quote: 'Obtenir un Devis',

    trust_title: 'Pourquoi Choisir Yuren Group',
    trust_gov: 'Fournisseur des Marchés Publics',
    trust_gov_desc: 'Fournisseur à long terme d\'équipements professionnels',
    trust_iso: 'Certification Qualité ISO',
    trust_iso_desc: 'Certifié système de management de la qualité ISO',
    trust_years: '36 Ans d\'Expérience',
    trust_years_desc: 'Fabrication d\'équipements militaires et policiers',
    trust_capacity: 'Forte Capacité de Production',
    trust_capacity_desc: 'Réponse rapide aux grandes commandes',

    about_title: 'À Propos de Jiangsu Yuren Group',
    about_subtitle: '36 Ans Consacrés aux Équipements Militaires et Policiers',
    about_desc1: 'Jiangsu Yuren Group a été fondé en 1990.',
    about_desc2: 'Après 36 ans de développement, fournisseur important dans le domaine.',
    about_stat1: 'Capacité Annuelle',
    about_stat2: 'Fondé en',
    about_stat3: 'Pays Exportés',
    about_stat4: 'Employés',

    contact_title: 'Contactez-Nous',
    contact_subtitle: 'Obtenez des devis professionnels',
    contact_name: 'Nom',
    contact_email: 'Email',
    contact_phone: 'Téléphone',
    contact_company: 'Entreprise',
    contact_message: 'Message',
    contact_submit: 'Envoyer',
    contact_address: 'Adresse',
    contact_address_val: 'Yancheng, Province du Jiangsu, Chine',
    contact_phone_val: '0515-86116888',
    contact_email_val: 'info@yurengroup.com',

    footer_desc: 'Jiangsu Yuren Group - Fabricant d\'Équipements Militaires et Policiers',
    footer_products: 'Produits',
    footer_company: 'Entreprise',
    footer_contact: 'Contact',
    footer_rights: 'Tous Droits Réservés',

    page_products_title: 'Produits',
    page_products_subtitle: 'Équipements militaires et policiers professionnels',
    page_shoes_title: 'Chaussures',
    page_shoes_subtitle: 'Chaussures militaires et policières professionnelles',
    page_uniforms_title: 'Uniformes Professionnels',
    page_uniforms_subtitle: 'Uniformes professionnels sur mesure',
    page_about_title: 'À Propos',
    page_manufacturing_title: 'Fabrication',
    page_contact_title: 'Contact',

    tactical_title: 'Série Bottes Tactiques',
    tactical_subtitle: 'Bottes d\'Entraînement au Combat Professionnelles',
    tactical_color_black: 'Noir',
    tactical_color_brown: 'Marron',
    tactical_color_sand: 'Sable',
    tactical_feature1: 'Antidérapant',
    tactical_feature2: 'Respirant',
    tactical_feature3: 'Haute Résistance',
    tactical_feature4: 'Lacement Rapide',
    tactical_spec_title: 'Spécifications',
    tactical_spec_upper: 'Matériau Supérieur',
    tactical_spec_sole: 'Matériau de Semelle',
    tactical_spec_height: 'Hauteur',
    tactical_spec_weight: 'Poids',

    military_title: 'Série Bottes Militaires',
    military_subtitle: 'Bottes Militaires Camouflage',
    military_color_camo: 'Camouflage',
    military_feature1: 'Design Camouflage',
    military_feature2: 'Léger',
    military_feature3: 'Imperméable',
    military_feature4: 'Confortable',

    uniform_title: 'Série Uniformes Professionnels',
    uniform_subtitle: 'Uniformes Professionnels Personnalisés',
    uniform_type1: 'Uniformes Police',
    uniform_type2: 'Uniformes Judiciaires',
    uniform_type3: 'Uniformes Sécurité',
    uniform_type4: 'Vêtements de Travail',

    mfg_title: 'Fabrication',
    mfg_subtitle: 'Installations de Production Modernes',
    mfg_capacity: 'Capacité de Production',
    mfg_workers: 'Employés',
    mfg_machines: 'Équipement de Production',
    mfg_quality: 'Système Qualité',

    breadcrumb_home: 'Accueil',
    breadcrumb_products: 'Produits',
    breadcrumb_shoes: 'Chaussures',
    breadcrumb_uniforms: 'Uniformes',
  },

  de: {
    nav_home: 'Startseite',
    nav_products: 'Produkte',
    nav_shoes: 'Schuhe',
    nav_shoes_tactical: 'Taktische Stiefel',
    nav_shoes_military: 'Militärstiefel',
    nav_uniforms: 'Uniformen',
    nav_about: 'Über Uns',
    nav_manufacturing: 'Fertigung',
    nav_contact: 'Kontakt',
    nav_get_quote: 'Angebot',

    hero_badge: 'Staatlich Zugelassener Lieferant',
    hero_title: 'Professioneller Militär- & Polizeiausrüstungshersteller',
    hero_subtitle: 'Jiangsu Yuren Group wurde 1990 gegründet. Seit 36 Jahren stellen wir militärische und polizeiliche Berufsausrüstungen her.',
    hero_cta_primary: 'Produkte Ansehen',
    hero_cta_secondary: 'Kontaktieren Sie Uns',
    hero_stat1: 'Jahreskapazität',
    hero_stat1_val: '6M+',
    hero_stat2: 'Gegründet',
    hero_stat2_val: '1990',
    hero_stat3: 'Exportländer',
    hero_stat3_val: '50+',
    hero_stat4: 'Mitarbeiter',
    hero_stat4_val: '2000+',

    products_title: 'Kernproduktlinien',
    products_subtitle: 'Professionelle Ausrüstung für Militär, Polizei und Regierungsbehörden',
    product_tactical_boots: 'Taktische Stiefel Serie',
    product_tactical_boots_desc: 'Professionelle Kampftrainingsstiefel',
    product_military_boots: 'Militärstiefel Serie',
    product_military_boots_desc: 'Militärische Tarnstiefel',
    product_uniforms: 'Berufsuniformen',
    product_uniforms_desc: 'Maßgeschneiderte Berufsuniformen',
    product_wool: 'Wollpullover Serie',
    product_wool_desc: 'Hochwertige Wollprodukte',
    product_fabric: 'Stoffmaterialien',
    product_fabric_desc: 'Hochwertige Stoffe',
    btn_view_details: 'Details Ansehen',
    btn_get_quote: 'Angebot Einholen',

    trust_title: 'Warum Yuren Group Wählen',
    trust_gov:: 'Staatlicher Lieferant',
    trust_gov_desc: 'Langzeitlieferant von professionellen Ausrüstungen',
    trust_iso: 'ISO Qualitätszertifizierung',
    trust_iso_desc: 'ISO Qualitätsmanagementsystem zertifiziert',
    trust_years: '36 Jahre Erfahrung',
    trust_years_desc: 'Herstellung von Militär- und Polizeiausrüstungen',
    trust_capacity: 'Starke Produktionskapazität',
    trust_capacity_desc: 'Schnelle Reaktion auf Großaufträge',

    about_title: 'Über Jiangsu Yuren Group',
    about_subtitle: '36 Jahre für Militär- & Polizeiausrüstungen',
    about_desc1: 'Jiangsu Yuren Group wurde 1990 gegründet.',
    about_desc2: 'Nach 36 Jahren Entwicklung wichtiger Lieferant.',
    about_stat1: 'Jahreskapazität',
    about_stat2: 'Gegründet',
    about_stat3: 'Exportländer',
    about_stat4: 'Mitarbeiter',

    contact_title: 'Kontaktieren Sie Uns',
    contact_subtitle: 'Professionelle Angebote erhalten',
    contact_name: 'Name',
    contact_email: 'E-Mail',
    contact_phone: 'Telefon',
    contact_company: 'Unternehmen',
    contact_message: 'Nachricht',
    contact_submit: 'Senden',
    contact_address: 'Adresse',
    contact_address_val: 'Yancheng, Provinz Jiangsu, China',
    contact_phone_val: '0515-86116888',
    contact_email_val: 'info@yurengroup.com',

    footer_desc: 'Jiangsu Yuren Group - Professioneller Militär- & Polizeiausrüstungshersteller',
    footer_products: 'Produkte',
    footer_company: 'Unternehmen',
    footer_contact: 'Kontakt',
    footer_rights: 'Alle Rechte Vorbehalten',

    page_products_title: 'Produkte',
    page_products_subtitle: 'Professionelle Militär- und Polizeiausrüstung',
    page_shoes_title: 'Schuhe',
    page_shoes_subtitle: 'Professionelle Militär- und Polizeischuhe',
    page_uniforms_title: 'Berufsuniformen',
    page_uniforms_subtitle: 'Maßgeschneiderte Berufsuniformen',
    page_about_title: 'Über Uns',
    page_manufacturing_title: 'Fertigung',
    page_contact_title: 'Kontakt',

    tactical_title: 'Taktische Stiefel Serie',
    tactical_subtitle: 'Professionelle Kampftrainingsstiefel',
    tactical_color_black: 'Schwarz',
    tactical_color_brown: 'Braun',
    tactical_color_sand: 'Sand',
    tactical_feature1: 'Rutschfest',
    tactical_feature2: 'Atmungsaktiv',
    tactical_feature3: 'Hochfest',
    tactical_feature4: 'Schnellverschluss',
    tactical_spec_title: 'Spezifikationen',
    tactical_spec_upper: 'Obermaterial',
    tactical_spec_sole: 'Sohlmaterial',
    tactical_spec_height: 'Höhe',
    tactical_spec_weight: 'Gewicht',

    military_title: 'Militärstiefel Serie',
    military_subtitle: 'Tarnmuster Militärische Stiefel',
    military_color_camo: 'Tarnung',
    military_feature1: 'Tarndesign',
    military_feature2: 'Leicht',
    military_feature3: 'Wasserdicht',
    military_feature4: 'Komfortabel',

    uniform_title: 'Berufs